/* eslint-disable */
require('./baby-boy')
require('./door')
require('./gender')
require('./hands')
require('./happy-poo')
require('./man')
require('./sad-poo')
require('./sanitary-pad')
require('./tampon')
require('./technics')
require('./warning')
require('./wheelchair')
require('./woman')
